### ISSUE TITLE
app.requestSingleInstanceLock can cause issues on mac app store submissions

### ISSUE THREAD

**Issue by mosatch** [glawson/electron-deeplink#15]
Checkout this issue: https://github.com/electron/electron/issues/15958

You probably want to wrap the call with a check for not process.mas

**Comment by glawson** [comment]
@mosatch - thank you!  I'll get that in this week.

**Comment by glawson** [comment]
resolved in #16

**Comment by glawson** [comment]
Wrapper is in place, but I'm leaving this issue open - will close when https://github.com/electron/electron/issues/15958 is resolved.

**Comment by glawson** [comment]
@mosatch - looks like https://github.com/electron/electron/issues/15958 is closed and we have a wrapper in place so I'm going to close this issue.  Please let me know if you are still running into issues.  Thanks.
