### ISSUE TITLE
Unable to Find Electron.app/Contents/Info.plist

### ISSUE THREAD

**Issue by lmick002** [glawson/electron-deeplink#17]
Thanks for the package! I've been looking for a package like this. When trying to run this package in the main.js, I get this error: 

Error: ENOENT: no such file or directory, open '/node_modules/electron/dist/Electron.app/Contents/Info.plist'
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Deeplink._this.setAppProtocol (~/node_modules/electron-deeplink/dist/index.js:49:32)
    at new Deeplink (~/node_modules/electron-deeplink/dist/index.js:116:40)
    at createMainWindow (~/app/main.dev.js:219:20)

Im running on electron "8.5.0"

**edit** my project does have 2 package.json: 1 for app-level and one for native packages and it looks like tits looking for electron in the wrong directory. Is there a way to set the electron path?

**Comment by lmick002** [comment]
I removed the extra directory i.e. "/app" and i haven't tested this on a production build yet but I am wondering -- could there be a way to set a relative path to electron directory since some projects might have different structures. Thanks

**Comment by glawson** [comment]
> I removed the extra directory i.e. "/app" and i haven't tested this on a production build yet but I am wondering -- could there be a way to set a relative path to electron directory since some projects might have different structures. Thanks

@lmick002 - yes!  I think that's a good idea.  Give me a couple of days and I'll add that in.

**Comment by glawson** [comment]
@lmick002  I added electronPath as an option in the config in #18 .  Where ever you instantiate Deeplink, you can now pass the electron path, relative to the app root.  

```const deeplink = new Deeplink({ app, mainWindow, protocol, isDev, debugLogging: true, electronPath: '/node_modules/electron/dist/Electron.app' });```

**Comment by glawson** [comment]
@lmick002 - please let me know if that worked out.

**Comment by lmick002** [comment]
@glawson I'll give it a shot and let you know!

**Comment by glawson** [comment]
@lmick002 - any luck?

**Comment by lmick002** [comment]
I was able to get it to work, but I had an issue with the Mac Store with Electron Builder that was preventing me from using the package in our app release build. But setting the electron URL worked in local development. @glawson

**Comment by glawson** [comment]
@lmick002 - thanks for the update.  I wonder if your MAS issue is related to #15 , it would be interesting to know.  As far as this issue, I'm going to go ahead and close it as resolved by #18.  Thanks!
