### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by rodrigomata** [glawson/electron-deeplink#19]
**Bug description**
After importing the `electron-deeplink` dependency, I get the following error on app startup:
```javascript
App threw an error during load
TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (webpack:///./node_modules/bindings/bindings.js?:178:16)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:82:48)
    at eval (webpack:///./node_modules/electron-deeplink/dist/index.js?:21:127)
```

**Steps To Reproduce**
1. Create a test app with `vue add electron-builder`
2. Add `electron-deeplink` dependency with `npm i -D electron-deeplink`
3. Require the dependency on the `main.js` file `import { Deeplink } from 'electron-deeplink'` 
4. App will break when trying to start

**Expected behavior**
Saw a couple of closed bugs in the repo `electron-builder` that suggested to add dependency as **externals**. So far I've already tried doing this without success:
```javascript
// vue.config.js
pluginOptions: {
    electronBuilder: {
      externals: ['electron-deeplink']
    }
  }
```

**Screenshot**
![Screen Shot 2020-10-06 at 20 56 21](https://user-images.githubusercontent.com/15259836/95278715-6dd65d80-0816-11eb-95b4-a4d59077165a.png)

**Environment:**
```
  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Not Found
    Firefox: 77.0.1
    Safari: 13.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.5.6 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.5.6 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-unit-jest: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.6 
    @vue/cli-service: ~4.5.0 => 4.5.6 
    @vue/cli-shared-utils:  4.5.6 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/test-utils: ^1.0.3 => 1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    jest-serializer-vue:  2.0.2 
    vue: ^2.6.11 => 2.6.12 
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4 
    vue-cli-plugin-tailwind: ~1.5.0 => 1.5.0 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-jest:  3.0.7 
    vue-loader:  15.9.3 (16.0.0-beta.7)
    vue-router: ^3.2.0 => 3.4.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.4.0 => 3.5.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by glawson** [comment]
@rodrigomata - I think you are right, seems related to and 'externals' issue.  I'm not to familiar with vue.config.js, but I'm assuming it's a vue builder that uses webpack under the hood?  Is there any webpack.config.js - or is it all within vue.config.js?

**Comment by rodrigomata** [comment]
That's right @glawson, `vue.config.js` is just a webpack wrapper. I used the guide [here](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/docs/guide/guide.md#native-modules), but that doesn't solve the issue.

**Comment by glawson** [comment]
@rodrigomata - did you happen to see this: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/598

**Comment by glawson** [comment]
@rodrigomata - try adding "bindings" to the externals in vue.config.js

**Comment by rodrigomata** [comment]
Hey thanks for the support. Already tried your suggestion without luck. Here's how my `vue.config.js` file looks like:
```javascript
module.exports = {
  configureWebpack: config => {
    config.devtool = 'source-map'
  },
  pluginOptions: {
    electronBuilder: {
      externals: ['bindings', 'electron-deeplink'],
    },
  },
}
```
Already tried adding also the suggestions on [this comment](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/598#issuecomment-580880268) from the link you shared and same story. 

I see this is the line failing according to the error stacktrace, am I probably missing something else?
```javascript
var electronDeeplink = os.platform() === 'darwin' ? require('bindings')('electron-deeplink.node') : require('./stub');
```

**Comment by glawson** [comment]
> Hey thanks for the support. Already tried your suggestion without luck. Here's how my `vue.config.js` file looks like:
> 
> ```js
> module.exports = {
>   configureWebpack: config => {
>     config.devtool = 'source-map'
>   },
>   pluginOptions: {
>     electronBuilder: {
>       externals: ['bindings', 'electron-deeplink'],
>     },
>   },
> }
> ```
> 
> Already tried adding also the suggestions on [this comment](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/598#issuecomment-580880268) from the link you shared and same story.
> 
> I see this is the line failing according to the error stacktrace, am I probably missing something else?
> 
> ```js
> var electronDeeplink = os.platform() === 'darwin' ? require('bindings')('electron-deeplink.node') : require('./stub');
> ```

Yeah - that line is correct.  I'll try to reproduce with vue in the next day or two, let you know.

**Comment by glawson** [comment]
@rodrigomata - I'm still looking into it but I wanted to mention something I've noticed so far that seemed odd.  The plugin, vue-cli-plugin-electron-builder, uses ''background.js" as the entrypoint for the main process and "main.js" for the renderer process, see [ folder-structure](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#folder-structure).  I noticed that you use main.js as the main process file (which is very typical/normal) - did you make changes to the vue.config.js to reflect that?  See [webpack-configuration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration)

**Comment by rodrigomata** [comment]
Hey @glawson, thanks for the suggestion. I did configured webpack in order to use `background.js` without luck so far. Will try a couple more of scenarios tomorrow to see if something succeeds.

**Comment by glawson** [comment]
@rodrigomata - I was able to get it to work.  I setup the instantiation like this
 ```
const deeplink = new Deeplink({ app, mainWindow: win, protocol: 'testvue', isDev: true, electronPath: '../node_modules/electron/dist/Electron.app' });
```
You can see the full setup here: https://github.com/glawson/deeplink-vue

**Comment by rodrigomata** [comment]
Hey @glawson, unfortunately I was unable to make it work even with your recommendation. The issue appears even before declaring the `Deeplink` instance, it happens when importing it, like so:
```javascript
const { Deeplink } = require('electron-deeplink')
```
Do you have any other idea of what could be happening?

PS. I followed the setup on [https://github.com/glawson/deeplink-vue](https://github.com/glawson/deeplink-vue) but I can't see how to configure `background.js`.

**Comment by glawson** [comment]
It is definitely an issue with externals, I've run into it with other
packages and electron builder.

**Comment by glawson** [comment]
@rodrigomata - I'm very sorry.  I didn't push all the changes up for https://github.com/glawson/deeplink-vue so you didn't get a working version.  Please take another look and let me know.

**Comment by rodrigomata** [comment]
Hey @glawson, thanks for updating the repo. Actually I think I made progress, since I noticed that I was able to clone and successfully build your project with npm; however, if I use yarn instead (which is what I'm using currently at my project), it fails with the error described in this issue. Funny thing is that I've already tried switching to npm in my project and it's failing, but I have a feeling its related to that. I'll do some more tests but feel free to close the issue, since I think it's not directly related to this repo.

**Comment by rodrigomata** [comment]
Hey I figured out what was the issue. I narrowed it down to this:

![Screen Shot 2020-10-20 at 18 48 32](https://user-images.githubusercontent.com/15259836/96656978-970ee780-1306-11eb-91f9-d1f47e98ded6.png)

I had some `electron` **dependencies** under **devDependencies**. I moved them to **dependencies** and it's working now (not with Yarn though).

**Comment by glawson** [comment]
@rodrigomata - thanks for the update.

**Comment by eden-lane** [comment]
I have the same problem, but I'm not using vue. I have webpack + React + yarn and I still get this error..
