### ISSUE TITLE
Getting this error when trying to use the package.

### ISSUE THREAD

**Issue by Rohithgilla12** [glawson/electron-deeplink#26]
Thanks for a great package but I am getting this error.

This happens when using with typescript.

Type 'Electron.App' is not assignable to type 'App'.

**Comment by glawson** [comment]
Hi @Rohithgilla12 - please forward alone the full error and your ts config.

**Comment by jony543** [comment]
I'm having the same issue when using typescript. Anyone managed to resolve it?

**Comment by glawson** [comment]
@Rohithgilla12 @jony543 - I'll be looking into this over the weekend.

**Comment by jony543** [comment]
Thanks. I actually found a workaround and I can post it later if anyone is interested. I think it was some type casting thing. Anyway, the issue should still be fixed.
________________________________

**Comment by Rohithgilla12** [comment]
@jony543 please do share the workaround

**Comment by glawson** [comment]
@Rohithgilla12, it is a type issue, I'm fixing the def.

**Comment by glawson** [comment]
@jony543 @Rohithgilla12 - fix in https://github.com/glawson/electron-deeplink/releases/tag/v1.0.7
