### ISSUE TITLE
Open a second instance after opening a deeplink on windows

### ISSUE THREAD

**Issue by nvdai2401** [glawson/electron-deeplink#27]
Hi, thanks for an awesome library!

My electron app opens another window after opening a deeplink on my window laptop. It does not happen on macOS. I checked the log file and found a message: `electron-deeplink: unable to lock instance`. Then I checked electron-deeplink source code and found this: https://github.com/glawson/electron-deeplink/blob/0300ba7e2e1cd39e0379030207cb5b92b62aa230/src/index.ts#L96

Can we prevent the app  from opening a second instance when opening a deeplink on windows?
I've attached a screen record and codes to give you more context about the problem:

- OS: Window 10, OS build: 19043.928

- `main.js`:
```js
const { app, BrowserWindow } = require("electron");
const { Deeplink } = require("electron-deeplink");
const isDev = require("electron-is-dev");

let mainWindow;
const protocol = isDev ? "dev-app" : "prod-app";
const deeplink = new Deeplink({
  app,
  mainWindow,
  protocol,
  isDev,
  debugLogging: true,
});

deeplink.on("received", (link) => {
  console.log("received link: ", link);
});

if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = () => {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
    },
  });

  mainWindow.loadURL("https://google.com");
};

app.on("ready", createWindow);

app.on("window-all-closed", () => {
  app.quit();
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

```

- `package.json`
```json
{
    "name": "electron-deeplink-example",
    "productName": "electron-deeplink-example",
    "version": "1.0.0",
    "description": "electron-deeplink-example app",
    "main": "./main.js",
    "scripts": {
        "start": "electron ."
    },
    "keywords": [],
    "author": {
        "name": "Geoff Lawson",
        "email": "jeffwithg@gmail.com"
    },
    "license": "MIT",
    "devDependencies": {},
    "dependencies": {
        "electron": "^13.1.7",
        "electron-deeplink": "^1.0.6",
        "electron-is-dev": "^1.2.0",
        "electron-log": "^4.2.3"
    }
}

```

https://user-images.githubusercontent.com/33539569/126765680-8ea770c0-4487-462d-ac7f-b0d537ee7011.mov

Thank you!

**Comment by glawson** [comment]
Hi @nvdai2401 - sorry for the late response.  I'll look into this over the weekend, let you know.

**Comment by nvdai2401** [comment]
@glawson Any updates?

**Comment by glawson** [comment]
Sorry @nvdai2401, I worked on and resolved another issue over the weekend so I didn't get to this yet.  I'll look at it soon.

**Comment by nvdai2401** [comment]
Figured it out. It's because the app creates a new window too fast before the second instance is forced to quit

To prevent the app from creating a second window, we just need to check the single instance lock before calling `createWindow` or wrap `createWindow` inside a `setTimeout`.

```js
if (app.requestSingleInstanceLock()) {
	createWindow()
}

// or

setTimeout(() => createWindow(), 500)


```

**Comment by Evanfeenstra** [comment]
you put that inside the `app.on("ready"` callback @nvdai2401? I'm still getting this error on Windows

**Comment by nvdai2401** [comment]
@Evanfeenstra Yes. This is my code:

```js
app.on('ready', () => {
  // disallow the app to create a new window when opening a deeplink
  if (app.requestSingleInstanceLock()) {
    createWindow()
  }
})
```
