### ISSUE TITLE
Message open 'Electron.app'

### ISSUE THREAD

**Issue by bierzorutas** [glawson/electron-deeplink#31]
Hi everybody,
thanks for your work in this project.

I have integrated and works fine, but when open the url that triggers the electron opening, message shown is showing a message not related with the app/project name and looks not very good to new users.

"Open Electron.app" is shown in title and button to open it. 

Is there a way to change this text or at least the "Electron.app" to something like "MyAppName.app" ??

Kind regards and thanks in advance

**Comment by glawson** [comment]
https://github.com/glawson/electron-deeplink#-deprecation-notice-
