### ISSUE TITLE
Cannot Install 

### ISSUE THREAD

**Issue by Flydexo** [glawson/electron-deeplink#36]
I installed the visual studio buildtools 2019 as required but I have a new error with node-gyp 
`npm ERR! code 1
npm ERR! path D:\backbeat\app\node_modules\electron-deeplink
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@16.13.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.7 found at "C:\Users\Flydexo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.32106.194) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\Flydexo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\backbeat\\app\\node_modules\\electron-deeplink\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Flydexo\\AppData\\Local\\node-gyp\\Cache\\16.13.0\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Flydexo\\AppData\\Local\\node-gyp\\Cache\\16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Flydexo\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\backbeat\\app\\node_modules\\electron-deeplink',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\backbeat\\app\\node_modules\\electron-deeplink\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: C:\Users\Flydexo\AppData\Local\node-gyp\Cache\16.13.0\common.gypi not found (cwd: D:\backbeat\app\node_modules\electron-deeplink) while reading includes of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:353:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\backbeat\app\node_modules\electron-deeplink
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok`

**Comment by esracoskun** [comment]
Hello @glawson , is there any progress?

**Comment by glawson** [comment]
Admittedly - this was lost in the shuffle.  Thank you for checking in, I'll
be looking into it.

**Comment by glawson** [comment]
The node-gyp package needs to be updated and the node version requirements set to node LTS.  I'm actively working on this as a v2.

**Comment by yahavf6** [comment]
any update?

**Comment by glawson** [comment]
Hi @yahavf6  - I'm actively working on an update.  eta is 2 weeks.

**Comment by rsm23** [comment]
Any updates?

**Comment by glawson** [comment]
Still working on v2 rewrite to fix issue.  Delayed due to holidays, work, etc.

**Comment by witcher112** [comment]
Hi,

I've created a new package based on electron-deeplink that resolves this issue by using prebuilds.

Available here: https://github.com/witcher112/electron-app-universal-protocol-client

PS. @glawson Maybe you'd like to consider v2 based on what I've done? I've put a lot of improvements in it (listed in README).

Thanks again for this fantastic package, without it, I wouldn't be able to write mine! :)

**Comment by glawson** [comment]
@witcher112 - thanks - that is very kind of you.  I'd finding that I have less and less time to support this repo, would you be interested in taking it over?

**Comment by witcher112** [comment]
@glawson why not :)

If possible I'd like to only have your opinion on whether to:
- create a v2 here
- deprecate it and redirect devs to my repo (as the API is much different)

**Comment by glawson** [comment]
@witcher112 - I'll just deprecate this one and redirect to your repo.

**Comment by witcher112** [comment]
Works fine for me!

About the timing, I propose we do it one month from now (we're releasing a production app featuring my package next week, and after one month I'll be confident to have users redirected to my package). I'll post you a notification here.

And of course, thank you for the support!

**Comment by glawson** [comment]
Hey @witcher112 - hope all is well!  Are you ready for me to redirect to your repo?

**Comment by witcher112** [comment]
@glawson Sure, we've deployed a few production-ready products with it and all seems to work fine (dev mode as well).

Feel free to and again thanks for your involvement!

**Comment by glawson** [comment]
https://github.com/glawson/electron-deeplink#-deprecation-notice-
