### ISSUE TITLE
Event 'received' is not fired on linux

### ISSUE THREAD

**Issue by geroale** [glawson/electron-deeplink#37]
**Version**
`electron-deeplink` 1.0.9
`electron` 17.1.2

**Operating System Version**
Linux Mint and Debian, but probably any Linux distro

**Expected Behavior**
When opening the deeplink scheme (`appname://...`) from the browser on a Linux OS, we should receive the event in the electron app, which is open and ready.

**Actual Behavior**
The deeplink is working fine on MacOS and Windows, but not on Linux.

**Code**
This is our code that handles the window, app and deeplink. I've omitted some parts that probably aren't related, like auto-updater and ipcMain.

```js
const { Menu, protocol, app, BrowserWindow, dialog, session, ipcMain } = require('electron')
const windowStateKeeper = require('electron-window-state')
const isDev = require('electron-is-dev')
const { autoUpdater } = require('electron-updater')
// const { autoUpdater, generateZipandBlockmap } = require('@imjs/electron-differential-updater')
const path = require("path")
const { getRandomAgent } = require('./userAgents')
const { bindEvents, bindWindowEvents, dismissWindowEvents } = require('./events')
const unhandled = require('electron-unhandled')
const { Deeplink } = require('electron-deeplink')
const contextMenu = require('electron-context-menu')

let win

function createWindow () {
  win = new BrowserWindow({
    ...
  })

  win.loadURL(isDev ? `http://localhost:3000` : path.join('file://', __dirname, '..', 'build/index.html'))
}

app.disableHardwareAcceleration()

const deeplink = new Deeplink({
  app,
  mainWindow: win,
  protocol: 'appname',
  isDev
})

deeplink.on('received', (link) => {
  console.log('received', link)
  win && win.webContents.send('onDeepLinkReceived', link)
})

app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required')

app.whenReady().then(() => {
  createWindow()

  app.on('activate', () => {
    if(BrowserWindow.getAllWindows().length === 0)
      createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
```

We are using `electron-builder` to package our app, and this is our configuration in `package.json`

```js
...
"build": {
    ...
    "protocols": [
      {
        "name": "appname",
        "schemes": [
          "appname"
        ]
      }
    ],
    ...
}
...
```

**Comment by labboy0276** [comment]
@geroale I noticed this as well.  The reason it is failing the way it is is due to the fact the custom schema is the last array item in Linux as it is in Windows.  Like in my case with our custom lando schema, the argv looks like:

```
[
  '/home/john/lando/desktop/node_modules/electron/dist/electron',
  '--enable-crashpad',
  '--allow-file-access-from-files',
  '/home/john/lando/desktop/build/main/main.js',
  'lando://installer'
]
```

The issue is on this line: https://github.com/glawson/electron-deeplink/blob/master/src/index.ts#L144

This logic should be reversed so that it reads:

```
    if (os.platform() === 'darwin') {
        this.emit('received', ...argv);
    } else {
        this.emit('received', argv.slice(-1).join(''));
    }
```

So that on linux it is grabbing the last argument and processing it correctly.

**Comment by labboy0276** [comment]
PR is here: https://github.com/glawson/electron-deeplink/pull/39

**Comment by geroale** [comment]
@labboy0276  It is fixed for us in this way, you're a life saver!

**Comment by glawson** [comment]
#39
