### ISSUE TITLE
Uninstall protocol

### ISSUE THREAD

**Issue by krysalead** [glawson/electron-deeplink#42]
Hi,

Thanks for the library.
I have a question on windows, we uninstall the application that was registering the protocol and we can still see the protocol inside the registry. Have you faced this issue and know how to solve that, any specific configuration?

I am using
electron@18.2.3
electron-builder@22.14.13 
electron-deepling@1.0.10

Thanks & regards

K

**Comment by glawson** [comment]
I'm sorry, there was never any 'clean-up' built in.  What are the reg keys and I'll look into it.  I'm working on a v2 right now, and I'll add in better support for Windows.

**Comment by devsibwarra** [comment]
Win10 registry search for my dev protocol shows
```
HKEY_CURRENT_USER\SOFTWARE\Classes\app-dev
    (Default)    REG_SZ    URL:app-dev

HKEY_CLASSES_ROOT\app-dev
    (Default)    REG_SZ    URL:app-dev
```

According to the [electron code](https://github.com/electron/electron/blob/0ee7f14190e75d0e7b669661c81235a4a2bfadb4/shell/browser/browser_win.cc#L491-L503) I think you only need to adjust the HKCU key

Could you use the Electron [app.removeAsDefaultProtocolClient](https://www.electronjs.org/docs/latest/api/app#appremoveasdefaultprotocolclientprotocol-path-args-macos-windows) to clean this up?

**Comment by glawson** [comment]
@devsibwarra or @krysalead - would either of you be interested in creating a powershell script to add and remove the reg keys?  I'm in the process of rebuilding the Mac `LaunchServices` entry, and the help would be appreciated.

**Comment by devsibwarra** [comment]
@glawson I live on a Mac environment, so I'd definitely be out of my element on Windows. Any reason to not the Electron native handler to cleanup the protocol registrations?

**Comment by glawson** [comment]
https://github.com/glawson/electron-deeplink#-deprecation-notice-
