### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [glawson/electron-deeplink#43]
**Node:** 14.19
**Environment:** Mac M1 Chip (Monterey - 12.4)
**Electron:** 12.2.3

I've just installed the package, and configured the DeepLink. But when I start the app it's looking for the node bindings at incorrect path so app crashes.

I've checked correct binary path is:
`/Users/ahmad-goraya/Documents/projects/repeato-studio/node_modules/electron-deeplink/build/releases/electron-deeplink.node`

**Expected:**
Package should search for bindings at correct location.

**Workaround:**
For now I manually copied the `build` directory from `node_modules/electron-deeplink` and put at root path then it starts working fine.

See attached screenshot for reference:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/15345707/175518821-0aa5fcb3-90ff-43a8-beaf-5834b22fede7.png">

**Comment by glawson** [comment]
Thanks for the report, I'll take a look asap.

**Comment by glawson** [comment]
The issue is related to the node-gyp version used in the package, and I need to up the node version requirements to LTS.  I'm actively working on this as a v2.

**Comment by olosegres** [comment]
I got the same error and solved it by excluding `electron-deeplink` from the bundle.
I'm using webpack, so I've added it to `externals` section of config.

When it is bundled `require('bindings')('native-file.node')` cannot determine coorect path because searching it near package dist folder (so it is not supported to be bundled).

**Comment by glawson** [comment]
https://github.com/glawson/electron-deeplink#-deprecation-notice-
